services:
  - type: web
    name: donation-telegram-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --threads 4 --timeout 60
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: MONGO_URL
        sync: false
      - key: CHANNEL_ID
        value: "-1003870548002"
      - key: ADMIN_IDS
        value: "8192070400"
      - key: QR_IMAGE_URL
        sync: false
      - key: QR_FILE_ID
        sync: false
      - key: BASE_URL
        sync: false
      - key: WEBHOOK_SECRET
        generateValue: true
